# Generated by Django 6.0.3 on 2026-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_bankaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
